export const FILL_ENDPOINT_DATA = "FILL_ENDPOINT_DATA";
export const FILL_ENVIROMNENT_DATA = "FILL_ENVIROMNENT_DATA";
export const ADD_PING_DATA = "ADD_PING_DATA";
export const ADD_RESPONSE_DATA = "ADD_RESPONSE_DATA";
export const ADD_RESPONSE_CONTENT_DATA = "ADD_RESPONSE_CONTENT_DATA";
